services:
  app:
    image: todo-frontend
    build:
      context: . # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    ports:
      - 3001:3000
    container_name: dev-frontend